apiVersion: v1
kind: Service
metadata:
  name: alloy-backend
spec:
  selector:
    app: alloy-backend
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: otlp-http
    - name: dashboard
      port: 12345
      protocol: TCP
      targetPort: dashboard
    