apiVersion: v1
kind: Service
metadata:
  name: otelcol-backend
spec:
  selector:
    app: otelcol-backend
  ports:
    - name: port-1
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: port-2
      port: 4318
      protocol: TCP
      targetPort: 4318
