apiVersion: v1
kind: Service
metadata:
  name: otelcol-backend
spec:
  selector:
    app: otelcol-backend
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: otlp-http
